# Generated by Django 4.1.5 on 2023-01-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
