# Generated by Django 4.1.5 on 2023-01-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_notice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='date',
        ),
    ]
