# Generated by Django 4.1.5 on 2023-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
